= openshift-operator-airlock-waf

== workflow(s)

image::http://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/baloise-incubator/openshift-operator-airlock-waf/master/workflow.puml[workflow]

== required metadata

We've discussed two ideas

- defining a https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/[CustomResourceDefinitions (CRD)] and listend for change events here
- listening for e.g. route (/ ingress) change events and annotation the e.g. route with required information to create / update / maintain a WAF mapping

== approach 1

=== idea

use and contribute: https://github.com/baloise-incubator/airlock-waf-kubernetes-openshift-integration

=== https://en.wikipedia.org/wiki/SWOT_analysis#Overview[SWOT] ergon

[cols="1,1", options="header"] 
|===
| Strengths 
| Weaknesses

| based on Spring

based on manufacturer know-how

modularized

in sync with manufacturer (API) changes

| partially reliant on internal / binary resources

| *Opportunities*
| *Threats*

| (distributed) maintenance (e.g. by manufacturer) in future
| upstream project direction no longer aligned with internal requirements

mitigation: *fork and maintain on our own*
|===

== approach 2 

=== idea

champion: build our own (lightweight) solution based on Quarkus and the Fabric8 Java Kubernetes client API.

=== https://en.wikipedia.org/wiki/SWOT_analysis#Overview[SWOT] baloise

[cols="1,1", options="header"] 
|===
| Strengths 
| Weaknesses

| potentially lightweight

exactly what we need

| offset to manufacturer (API) changes

(new) use cases must be implemented and maintained by our own

| *Opportunities*
| *Threats*

| exemplify new technology within small and well defined scope
| new framework technology without TIP & supporter

mitigation: *find supporter and file TIP*

incompatible (API) changes by manufacturer

mitigation: *make open-source and inform manufacturer about it*

|===
