apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waf-mapping-view
  labels:
    app: baloise-airlock-waf-operator
rules:
  - apiGroups: ["stable.baloise.ch"]
    resources: ["wafmappings"]
    verbs: ["get", "list", "watch"]