apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: waf-mapping-operator-role-binding
  labels:
    app: baloise-airlock-waf-operator
subjects:
  - kind: ServiceAccount
    name: waf-mapping-operator-account
    namespace: waf-mapping-operator-dev
roleRef:
  kind: ClusterRole
  name:  waf-mapping-edit
  apiGroup: rbac.authorization.k8s.io